apiVersion: v1
kind: Service
metadata:
  name: my-static-site-service
spec:
  type: NodePort
  selector:
    app: my-static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
